# Generated by Django 5.0.3 on 2024-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRUDOperation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kigo", models.CharField(max_length=100)),
                ("temp", models.FloatField(max_length=150)),
                ("hum", models.FloatField(max_length=150)),
                ("sun", models.FloatField(max_length=150)),
                ("co2", models.FloatField(max_length=150)),
                ("water", models.FloatField(max_length=150)),
                ("time", models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name="ChimModel",
        ),
    ]
